### PR TITLE
Rebuild requirements.txt to upgrade secondary deps

### PR DESCRIPTION
**Pull request by jwhitlock**
After removing `requirements.txt` and running `make update_deps`, many secondary packages (not listed in `requirements.in`) were updated, and some additional distributions were found.

This is a lot of changes! I'm curious if any issues are found by the PR tester.

## Packages updated
* aiohttp 3.7.4 → 3.8.4
* alabaster 0.7.12 → 0.7.13
* amqp 5.0.9 → 5.1.1
* async-timeout 3.0.1 → 4.0.2
* attrs 20.3.0 → 23.1.0
* babel 2.9.1 → 2.12.1
* beautifulsoup4 4.11.1 → 4.12.2
* botocore 1.27.22 → 1.27.96
* build 0.8.0 → 0.10.0
* cachetools 5.2.0 → 5.3.0
* certifi 2020.11.8 → 2022.12.7
* chameleon 3.8.1 → 4.0.0 
* charset-normalizer 2.0.4 → 2.1.1
* click 8.0.4 → 8.1.3
* click-didyoumean 0.0.3 → 0.3.0
* coverage 5.3 → 7.2.3
* datadog 0.39.0 → 0.45.0
* docutils 0.16 → 0.17.1
* exceptiongroup 1.0.0 → 1.1.1
* faker 5.0.0 → 18.4.0
* greenlet 1.1.1 → 1.1.3.post0
* hiredis 1.1.0 → 2.2.2
* hupper 1.10.2 → 1.12
* idna 2.10 → 3.4
* imagesize 1.2.0 → 1.4.1
* iniconfig 1.1.1 → 2.0.0
* iso8601 0.1.13 → 1.1.0
* jinja2 2.11.3 → 3.1.2
* jmespath 0.10.0 → 1.0.1
* kombu 5.2.3 → 5.2.4
* mako 1.2.2 → 1.2.4
* markupsafe 1.1.1 → 2.1.2
* multidict 5.1.0 → 6.0.4
* mypy-extensions 0.4.3 → 1.0.0
* packaging 21.3 → 23.1
* pastedeploy 2.1.1 → 3.0.1
* pathspec 0.9.0 → 0.11.1
* plaster 1.0 → 1.1.2
* plaster-pastedeploy 0.7 → 1.0.1
* platformdirs 2.3.0 → 3.2.0
* pluggy 0.13.1 → 1.0.0
* prompt-toolkit 3.0.8 → 3.0.38
* pygments 2.7.4 → 2.15.1
* python-dateutil 2.8.1 → 2.8.2
* pytz 2021.3 → 2023.3
* six 1.15.0 → 1.16.0
* snowballstemmer 2.0.0 → 2.2.0
* soupsieve 2.0.1 → 2.4.1
* sphinxcontrib-applehelp 1.0.2 → 1.0.4
* sphinxcontrib-htmlhelp 2.0.0 → 2.0.1
* tomli 1.2.1 → 2.0.1
* wcwidth 0.2.5 → 0.2.6
* webob 1.8.6 → 1.8.7
* wheel 0.37.1 → 0.40.0
* wrapt 1.13.3 → wrapt 1.15.0
* yarl 1.6.3 → 1.8.2
* zope-deprecation 4.4.0 → 5.0
* zope-event 4.5.0 → 4.6
* zope-interface 5.2.0 → 6.0
* pip 22.0.3 → 23.1
* setuptools 59.6.0 → 67.6.1

## Packages added
* aiosignal 1.3.1 - brought in by aiohttp
* frozenlist 1.3.3 - brought in by aiohttp, aiosignal
* pyproject-hooks 1.0.0 - brought in by build

## Packages removed
* chardet 3.0.4 - no longer used by aiohttp 
* decorator 4.4.2 - no longer used by datadog
* pep517 0.10.0 - no longer used by build
* pyparsing 2.4.7 - no longer used by packaging
* text-unidecode 1.3 - no longer used by faker
* toml 0.10.2 - no longer used by coverage
* typing-extensions 3.1.0.0.2 - no longer used by aiohttp

## Packages with new distributions / hashes
* gunicorn 20.1.0 - added wheel
* setproctitle 1.3.2 - added many wheels

### CODE REVIEW

**Comment by bsieber-mozilla** [comment]
Thanks for this PR @jwhitlock; 

_I'll take some time later this week to poke the build/tests on your fork:branch_

**Comment by jwhitlock** [comment]
I'm surprised and pleased that the tests passed. I think dependabot has _not_ been updating secondary dependencies, which is... ok.

We could be hopeful and merge and watch what it does in stage.

Or, I could break it up:

* Updates that should only impact the development process, and should be safe (click, others)
* Updates that should be OK based on experience (certifi, pytz, botocore, others)
* See what is left and decide how to break it up

**Comment by bsieber-mozilla** [comment]
> We could be hopeful and merge and watch what it does in stage.

I think this would be ok; if staging is unstable, I imagine we could rollback and take the `break it up` approach

**Review by bsieber-mozilla — APPROVED** [review]

**Comment by bsieber-mozilla** [comment]
Currently the version in use on staging is from ci build 4135.

The sentry link in the Dev docs points to aws--and `location-*` sentry.io projects are really quiet; I wonder if this was migrated to the new instance

**Comment by bsieber-mozilla** [comment]
Ooh; looks like the build number JUST flipped to the build associated with this change (4140 // aca6b5fe6aea845ba94c114b21f1955ae43dacaa)

**Pull request merged**
