### PR TITLE
Get TravisCI building on ckolos/dammit branch

### PR DESCRIPTION
**Pull request by jwhitlock**
Get the 1.5.1 build in ckolos/dammit (the deployment branch) working again:

- Use trusty build
- Disable the built-in boto configuration
- Ensure MySQL starts
- Cherry-pick the MaxMindDB update from d3e8983a, minus the 2.x vendored stuff
- Add a badge to the README

This should fix issue #831.

### CODE REVIEW

**Comment by hannosch** [comment]
Btw. There is a 1.5.x branch, which is almost the same as ckolos/dammit. The former was meant to be the old production branch, while master got dockerized and got some css changes to adopt the “new” Mozilla logo and style.

**Comment by jwhitlock** [comment]
@ckolos @willkg how do you feel about using the [1.5.x branch](https://github.com/mozilla/ichnaea/tree/1.5.x) as the deployment branch rather than `ckolos/dammit`?

**Comment by willkg** [comment]
I'm inclined to stick with `ckolos/dammit` unless you feel confident that you can do the switch with low risk. We're probably not going to touch this branch after September, so I don't feel compelled to clean it up. Beyond that, I don't have any strong opinions and I'm +1 on whatever you choose--you know more about the specifics than I do.

**Comment by ckolos** [comment]
We'll need to merge over the verbiage changes from dammit (smh, if I had known we'd be using this I would have used a better name), but I'm more than willing to try a deploy from the 1.5.x branch to test in stage.

**Comment by jwhitlock** [comment]
I'm going to merge this, then open a PR back to 1.5.x

**Pull request merged**
